name: Automatic Publication

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  validate-and-publish:
    name: Validate and build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          # Convert Editor's Draft to Working Draft!
          W3C_BUILD_OVERRIDE: |
            specStatus: CG-DRAFT
